### ISSUE TITLE
Can't edit "CanRawFilter" from GUI

### ISSUE THREAD

**Issue by fenugrec** [GENIVI/CANdevStudio#121]
I'm running 0.3 @ 4cf77f66 on Arch Linux. After adding a CanRawFilter element, I can't edit it : I can add, delete lines; change between "Accept" and "Drop", but impossible to change the ID and Payload fields. Tried clicking, pressing enter, space, backspace, numbers, arrows, no effect.

Qt-5.12 on Arch linux. Let me know if you need more information.

Hints ?

**Comment by rkollataj** [comment]
The last line in CanRawFilter is meant to be not editable. It's purpose is to catch all unmatched frames from any other rows that can be added above. After adding new line you should be able to edit it. 

It seems that the way it is working now is a bit confusing. I will think about making it more clear. Some HowTo will help for sure...

**Comment by fenugrec** [comment]
Ah ! I didn't even think of trying to edit a newly added line. How about graying out the catch-all line ? Or, making it a seperate UI element just outside the list and visibly not part of it.

**Comment by rkollataj** [comment]
@fenugrec I have tweak interface a bit. I hope it is more usable now. Let me know about any problems and thanks again for reporting!

**Comment by fenugrec** [comment]
Just tried your fix. Looks great, thanks!
