### ISSUE TITLE
can't drag+drop elements onto canvas

### ISSUE THREAD

**Issue by fenugrec** [GENIVI/CANdevStudio#122]
On 0.3 @ 4cf77f66  : I can't drag and drop elements onto canvas; I need to right-click on the canvas and select the elements. See [screenshot](http://imgbin.ca/image.uploads/16-01-2019/original-fdaf185017fe7ca1525126b89fda1aa4.jpg) of attempt at dragging elements.

Qt-5.12 on Arch linux. Let me know if you need more information.

**Comment by rkollataj** [comment]
Issues fixed. Thanks for reporting!
