### ISSUE TITLE
[Support Request] How to configure PCAN-USB bitrate on CANdevStudio Win32

### ISSUE THREAD

**Issue by jogo-** [GENIVI/CANdevStudio#128]
I'm trying to use the latest Win32 Prebuilt package from Bintray :
**CANdevStudio-0.3.875ac1f-win32-standalone** (https://bintray.com/rkollataj/CANdevStudio/download_file?file_path=CANdevStudio-0.3.875ac1f-win32-standalone.7z)

**OS** : Windows 10 x64 Version 1703 (15063.1563)
**CAN Hardware** : PeakCAN PCAN-USB (Drivers: 4.1.4.16279 KMDF 1.9, x64, Desktop)

How can I configure the actual PCAN-USB bitrate in CANdevStudio ? Using a 'plugin.json' file or somewhere in the GUI ?

Thank you for your support

**Comment by rkollataj** [comment]
I have not tested CANdevStudio with PCAN, but as far as I can see it requires some additional settings. There is currently no way to pass additional configuration parameters via GUI. When working on Linux I configure CAN interface via system utility (iproute2) and than just connect CANdevStudio to already configured interface. I am wondering if you could try similar approach? Does Peak provides some third party configuration utility?

**Comment by jogo-** [comment]
According to the [PEAK-System CAN-API Comparison](https://www.peak-system.com/Comparaison-APIs-CAN.392.0.html?&L=1), the hardware configuration is only possible via application when using the PCAN-Basic, while it is possible via control panel or application when using PCAN-Developer 4.

So myquestion is now the following:
Would you mind please adding this PCAN-Basic hw config using a 'plugin.json' file or a GUI dialog/menu?

Thank you for your support

**Comment by rkollataj** [comment]
I don't have too much time currently as I am starting week long holidays tomorrow. I have prepared quick solution for you to test (https://github.com/rkollataj/CANdevStudio/tree/device_config). There is additional "configuration" row in CanDevice config window (the same that you are using for setting up backend and interface). Let me know if it works for you when you are using:

backend: peakcan
interface: usb0
configuration: BitRateKey = 500000  //(or whatever speed you need)

**Comment by jogo-** [comment]
Could you just provide the Win32 prebuilt isolated exe (shortest .7z) from Bintray (or elsewhere), as I still can't build for the moment ?

Thank you for your support

**Comment by rkollataj** [comment]
There you go:

[CANdevStudio-0.3.fbb4446-win32.zip](https://github.com/GENIVI/CANdevStudio/files/2793424/CANdevStudio-0.3.fbb4446-win32.zip)

Let me know if it works.

**Comment by jogo-** [comment]
Tested with BitRateKey = 250000 and it works like a charm !

Thanks a lot !

**Comment by jogo-** [comment]
On your branch (https://github.com/rkollataj/CANdevStudio/tree/device_config), you will see 2 new PR from me.

**Comment by jogo-** [comment]
Tested successfully using PassThruCAN Plugin configured for "PEAK - PCAN" from PEAK-System :
backend: passthrucan
configuration: BitRateKey = 250000
interface: PCANPT32

And tested successfully using PassThruCAN Plugin configured for "SIE_CANUSB" from Sontheim Industrie Elektronik GmbH :
backend: passthrucan
configuration: BitRateKey = 250000
interface: CANUSB

Great job !

**Comment by rkollataj** [comment]
Great to hear that! I still need to add unit tests for this code so it will take some more time until it will be available on master branch. I will keep this thread open till that time. 

Thanks for PRs.

**Comment by jogo-** [comment]
Could you please also add to the configuration row the possibility to switch between SFF and EFF? Since your current solution only supports the default frame format of each interface.

**Comment by rkollataj** [comment]
@jogo- In the future please open new issues for new problems/requests. Both SFF and EFF frames are supported. Any frame with an ID 0x7FF is an extended frame.

Example:
![image](https://user-images.githubusercontent.com/19871188/52520705-ddc0c900-2c6c-11e9-934b-474fe56afb6c.png)

**Comment by rkollataj** [comment]
Fix on master branch. 

Binaries:
https://bintray.com/rkollataj/CANdevStudio/master/448f2f9#files
