### ISSUE TITLE
[Feature Request] Change display format of CAN message Id according to its frame format SFF/EFF

### ISSUE THREAD

**Issue by jogo-** [GENIVI/CANdevStudio#137]
I'm using the brand new : CANdevStudio v0.4.0 win32-standalone

Exemple of CAN message id 2047d (0x7FF) :
To be displayed as '0x7FF' only for SFF
To be displayed as '0x000007FF' for EFF

**Comment by rkollataj** [comment]
You're right. I will fix that.

**Comment by jogo-** [comment]
Tested your CANdevStudio-0.4.260e330-win32-standalone version and everything works fine.
Thank you and keep up the great work !
