### ISSUE TITLE
[Feature Request] Add support for sending CAN message Id [0..0x7FF] with any frame format SFF or EFF

### ISSUE THREAD

**Issue by jogo-** [GENIVI/CANdevStudio#138]
I'm still using the brand new : CANdevStudio v0.4.0 win32-standalone

Example of CAN message id 2047d (0x7FF) :
Can be sent as '0x7FF' only for SFF
Can be sent as '0x000007FF' for EFF

Maybe adding a dedicated checkbox:
- [x] EFF
- [ ] SFF

**Comment by rkollataj** [comment]
I will try to fix that, thanks for reporting. I will probably follow approach from cansend (from Can Utils) i.e. 
- 3 digits <= 0x7ff -  SFF
- 3 digits > 0x7ff - EFF
- 8 digits - EFF

**Comment by rkollataj** [comment]
PR merged. Let me know if it works ok from your pov.

https://bintray.com/rkollataj/CANdevStudio/master/260e330#files

**Comment by jogo-** [comment]
Tested your CANdevStudio-0.4.260e330-win32-standalone version and everything works fine.
Thank you and keep up the great work !
