### ISSUE TITLE
[Feature Request] Add support for automatic PassThruCAN device discovery on Windows

### ISSUE THREAD

**Issue by jogo-** [GENIVI/CANdevStudio#142]
Only on Windows (32/64bits), when selecting the `backend: passthrucan`, it should be easier to select the proper CAN adapter by providing the list (as a drop-down list) of all available CAN adapters accessible as documented here:
https://github.com/qt/qtserialbus/blob/670f912fbc08002ac063504755fc7705931e0d6e/src/serialbus/doc/src/passthrucan.qdoc#L66-L76
For my previous tests, I had no other choice than to look for the actual CAN adapter name in the Windows registry myself.

**Comment by rkollataj** [comment]
I can see that enumeration of devices should be available since Qt 5.9 https://bugreports.qt.io/browse/QTBUG-54298. I am putting this on my TODO list.

**Comment by jogo-** [comment]
Would you mind please sharing with us your TODO list here ? Maybe on a dedicated README.md chapter or a Wiki page ?
Thank you.

**Comment by rkollataj** [comment]
I have added relevant issues for ToDo items.
