### ISSUE TITLE
CanSignalSender

### ISSUE THREAD

**Issue by rkollataj** [GENIVI/CANdevStudio#147]
Port CanSignalSender from [signals](https://github.com/GENIVI/CANdevStudio/tree/signals) to master branch.

CanSignalSender enables to send CAN signals.

**Comment by fadhel086** [comment]
Hi,
since the porting is in inital stage ..
Is it possible to incorporate a loop checkbox and interval in CanSignalSender similar to CanRawSender.
Usecase:
For booting vehicle instrument cluster one needs to send multiple signals in a loop in prescribed time.

**Comment by rkollataj** [comment]
Hi @fadhel086. The reason why there is no cycle in CanSignalSender is the fact that cycle is attribute of a CAN frame rather than signal itself. All signals within frame needs to have the same cycle. You can achieve what you need with CanSignalData. Once you will have DBC loaded open signal list (double click on CanSignalData component) and press "squash" button (top left). You will get possibility to set cycle per can frame. You can set initial value too and still use CanSignalSender to change value of a signal within a frame.

Note that currently you need to save simulation after each initial value or frame cycle change to take effect. 

I realise that current way of handling this may be a bit confusing... I will rethink it when porting. I hope to get some support soon to finaly move signal handling to master.

**Comment by fadhel086** [comment]
Thanx for the reply ..
I shall tell the team here to test this ...
I do understand you are contributing here in your free time...
I do hope we shall be able to contribute here at some stage in future..

**Comment by rkollataj** [comment]
@fadhel086 @chrissunny94  I have ported CanSignaSender and CanSignalEncoder to the master branch. I aimed to improve handling in comparison to what is available in signals branch. I also updated README to give some simple guide for components I have added. 

I hope you will get a chance to test new changes. Feel free to report new issues/PR in case of suggestions/errors.
