### ISSUE TITLE
[Feature Request] Add support for sending and receiving CAN Remote frames

### ISSUE THREAD

**Issue by jogo-** [GENIVI/CANdevStudio#152]
Currently, remote frames are received and displayed as normal data frames while a remote flag should identify such remote frames.
Sending remote frames is not yet possible.

**Comment by jogo-** [comment]
I guess it also closes this "To do" card : https://github.com/GENIVI/CANdevStudio/projects/1#card-18324986

**Comment by rkollataj** [comment]
Correct. Fixed now. Thanks.
