### ISSUE TITLE
Pi Compatibility

### ISSUE THREAD

**Issue by snoop911** [GENIVI/CANdevStudio#178]
Building this on a Pi (Stretch with Qt 5.12.3) seems to complete fine, but executing files/./CANdevStudio.sh it reports:

./CANdevStudio.sh: 15: ./CANdevStudio.sh: /home/pi/CANdevStudio/files/./CANdevStudio: not found

Is there a known compatibility issue between CanDevStudio and the Pi Zero (using a CAN hat)?

**Comment by rkollataj** [comment]
I have never tried to run CDS on Pi. I believe it should work though. Could you show me an output of following commands:

ls -al /home/pi/CANdevStudio/files
file /home/pi/CANdevStudio/files/CANdevStudio
ldd /home/pi/CANdevStudio/files/CANdevStudio

**Comment by snoop911** [comment]
It doesn't look like anything is there:

pi@raspberrypi:~/CANdevStudio/build $ ls -al /home/pi/CANdevStudio/files
total 24
drwxr-xr-x  5 pi pi 4096 Jun  1 12:26 .
drwxr-xr-x 12 pi pi 4096 Jun  1 12:40 ..
-rwxr-xr-x  1 pi pi  439 Jun  1 12:26 CANdevStudio.sh
drwxr-xr-x  2 pi pi 4096 Jun  1 12:26 css
drwxr-xr-x  4 pi pi 4096 Jun  1 12:26 images
drwxr-xr-x  2 pi pi 4096 Jun  1 12:26 json
pi@raspberrypi:~/CANdevStudio/build $ file /home/pi/CANdevStudio/files/CANdevStudio
/home/pi/CANdevStudio/files/CANdevStudio: cannot open `/home/pi/CANdevStudio/files/CANdevStudio' (No such file or directory)
pi@raspberrypi:~/CANdevStudio/build $ ldd /home/pi/CANdevStudio/files/CANdevStudio
ldd: /home/pi/CANdevStudio/files/CANdevStudio: No such file or directory
pi@raspberrypi:~/CANdevStudio/build $

Yet, running cmake .. , and make , seem to complete fine:
https://pastebin.com/4rfshyxM

**Comment by rkollataj** [comment]
I got slightly confused, but I think I understand the problem now. CANdevStudio.sh script is useful whenever you are trying to run "standalone" version of prebuilt packages. These packages can be downloaded from [here](https://bintray.com/rkollataj/CANdevStudio/releases/v0.4.1#files).

When you are building CDS on your own you should be able to run it simply from build directory:

[remol@ES5470 build]$ pwd
/home/remol/Projects/CANdevStudio/build
[remol@ES5470 build]$ ./src/gui/CANdevStudio&

I hope this helps

**Comment by snoop911** [comment]
Thanks, that is good to know!  The GUI now comes up, but for some reason it doesn't list anything under the Device Layer / CanDevice.. 

However, 'ifconfig' shows can0, and I'm able to transmit using cansend / SavvyCan, so the (Microchip) CAN hat seems working.  Any idea why CDS doesn't recognize it?  The Pi's Stretch image is using kernel 4.14.98+.

**Comment by rkollataj** [comment]
[QtCanBus](https://doc.qt.io/qt-5/qtcanbus-backends.html) that is a core of CDS depends on plugins. These plugins are loaded during application startup. Example from my PC:

remol@ES5470:~ $ ls /usr/lib/qt/plugins/canbus 
libqtpassthrucanbus.so  libqtsocketcanbus.so  libqtvirtualcanbus.so
libqtpeakcanbus.so      libqttinycanbus.so

If you have Qt plugins in place and then drag and drop CanDevice you should be able to select these plugins from CanDevice properties window. For Microchip you should select socketcan backend.

Support for Microchip comes with 4.12 kernel. Besides if your system shows can interface (either via ifconfig or ip link) your kernel is just fine. 

One more thing is CAN interface configuration. As SocketCAN plugin does not support bitrate configuration you need to do this outside of CDS application. Details can be found here: https://doc.qt.io/qt-5/qtserialbus-socketcan-overview.html
