### ISSUE TITLE
CanRawSender doesn't update frame data unless "Send" is toggled

### ISSUE THREAD

**Issue by erikboto** [GENIVI/CANdevStudio#179]
Steps to reproduce:

1. Set up a CanRawSender with a repeating frame, "Id: 111, Data: 00000000, Loop: checked, Interval: 100".
2. Enable it by clicking "Send"
3. Change the Id to 112.
4. Start simulation

The CanRawSender will now send frames with Id 111 and not Id 112, until  "Send" is set to off and then on again.

I had a quick look at the code, and it looks like only NewLineManager::SetSendButtonState() is called on changes to Id, Data etc, but the actual set up of the frame is only done in NewLineManager::SendButtonPressed().

**Comment by rkollataj** [comment]
Good catch and many thanks for the fix!
