### ISSUE TITLE
[Archlinux packaging] - disable tests

### ISSUE THREAD

**Issue by fenugrec** [GENIVI/CANdevStudio#188]
Hi,
I'm updating the PKGBUILD for Arch, and I noticed that since a231e8e824e80a9bcb735c746ee34a23cf9cecfc , "make install" copies a lot of gmock and gtest files which I think are really not necessary for the typical user.

So I tried to invoke cmake with "-DWITH_TESTS=OFF", but it looks like that option isn't forwarded to  3rdParty/CANdb  (I think that is the submodule responsible for those gtest files).

Any ideas / did I forget an option ?

Thanks!

**Comment by rkollataj** [comment]
Hi @fenugrec. I have just commited a fix to the master branch. Let me know if it solves the issue.

Thanks for maitaining a package for Arch!

**Comment by fenugrec** [comment]
Works perfect, thanks for the quick fix !
