### ISSUE TITLE
Wrong instruction for Cannelloni configuration

### ISSUE THREAD

**Issue by pamo-mobica** [GENIVI/CANdevStudio#189]
IP address passed to cannelloni app should be address of remote machine (192.168.0.2):
`cannelloni -I can0 -R 192.168.0.1 -r 30000 -l 20000`
Also CANdevStudio configuration should use socket can as backend and con0 for interface.

Below is patch with those changes:
[0001-Fix-Cannelloni-configuration-instruction.patch.tar.gz](https://github.com/GENIVI/CANdevStudio/files/3874124/0001-Fix-Cannelloni-configuration-instruction.patch.tar.gz)

**Comment by rkollataj** [comment]
There are two ways to use Cannelloni with CANdevStudio - with and without Qt canbus plugin. The issue is that the plugin was not built with CDS as there was an error in CMake file. I have corrected the error and also added some clearer (I hope!) description to readme file.

Thanks for reporting!
