### ISSUE TITLE
[Feature Request] Add support for slcan protocol

### ISSUE THREAD

**Issue by AkR7F1X** [GENIVI/CANdevStudio#195]
Add support for slcan protocol with serial device without slcand for Windows. 

I reprogrammed the open hardware device [CanDybug](https://github.com/IntergatedCircuits/CanDybugFW) to support the slcan protocol and I would like to use it on Windows.
Maybe I will find the time in the next few weeks, then I can implement it if the request is accepted.

**Comment by rusoku** [comment]
I will try to add CANAL interface.

**Comment by rkollataj** [comment]
@AkR7F1X @rusoku  Your contributions are more than welcome!

As CANdevStudio is Qt based the best way to add new devices is to follow https://doc.qt.io/qt-5/qtcanbus-backends.html. Of course it may take some time until new plugins will be accepted to official Qt release. In the mean time I am ok to add your plugins to be build together with CANdevStudio as [qtCannelloniCanBus](https://github.com/tuvok/qtCannelloniCanBus/tree/db0e8745732fd60dc2821ac19a09fea13f6ccbb4). Take a look at CANdevStudio/3rdParty/qtCannelloniCanBus as a example/reference.

**Comment by AkR7F1X** [comment]
Oh shit 😄 
I think I underestimated the amount of work a bit.
I’ll take a look at canelloni first...

**Comment by rkollataj** [comment]
Maybe I've overcomplicated it in my description :) qtCannelloni plugin is about 200 LoC. 

To make it clear you don't have to upstream anything to Qt. qtCannelloni was created more than 2 years ago and since that time no updates were necessary.

**Comment by rusoku** [comment]
wow it seems like CANdevStudio use my old good USB2CAN converter too.Nice!
https://youtu.be/1TfAyg6DG04?t=35
Ok then I will start from Qt CAN bus driver.I will add new stuff like RUSOKU CAN FD devices as well.

> As CANdevStudio is Qt based the best way to add new devices is to follow https://doc.qt.io/qt-5/qtcanbus-backends.html. Of course it may take some time until new plugins will be accepted to official Qt release. In the mean time I am ok to add your plugins to be build together with CANdevStudio as [qtCannelloniCanBus](https://github.com/tuvok/qtCannelloniCanBus/tree/db0e8745732fd60dc2821ac19a09fea13f6ccbb4). Take a look at CANdevStudio/3rdParty/qtCannelloniCanBus as a example/reference.

**Comment by rkollataj** [comment]
@rusoku Actually I have purchased it from https://www.8devices.com/products/usb2can but it does look familiar. Is it your desing? :)

I cannot see any CAN FD device in your shop yet. Are you still working on it? CANdevStudio will require some tweaks to make CAN FD use efficient (e.g. fix viewer to be able to show 64 bytes of payload). In principle though QCanBusFrame has support for CAN FD frames so it shouldn't be that hard.

**Comment by rusoku** [comment]
I developed this converter for VSCP home automation long time ago ;-)
Later 8dev was selling this converter and I worked for 8dev on WiFi modules hardware (Carambola,Rambutan,Jalapeno , etc...)
At his moment I am owner of Rusoku technologies.
CAN FD devices are on developing phase now.Works but springs and gears still exploding ;-)
(STM32H750+4x MCP2518)

**Comment by rkollataj** [comment]
Sounds cool. Good luck!

@rusoku, @AkR7F1X I am closing this topic as we drifted a bit from the main subject :) Feel free to open new issue if required or even better - Pull Request :)
