### ISSUE TITLE
DBC parsing error

### ISSUE THREAD

**Issue by novalisek** [GENIVI/CANdevStudio#196]
Hi,
I have CDS 1.0.0. installed on W10, I have problem parsing some .DBC files -  I downloaded "ford_cgea1_2_bodycan_2011.dbc" and "ford_cgea1_2_ptcan_2011.dbc" from opendbc https://github.com/commaai/opendbc/  . I can open first file without problem, second one is not parsed and no messages are shown in CanSignalData

**Comment by rkollataj** [comment]
I think that your problem may be related to https://github.com/commaai/opendbc/issues/151. Try to reorder or delete sections that does not follow specification.

**Comment by novalisek** [comment]
I also tried to convert the files in Busmaster convert utility, there were problems with both of them because they had spaces instead of tabs. I opened them in CANdb++ from Vector, saved them again and then Busmaster had no problem converting them. Also CDS opened them fine, so it seems CANdb++ "fixed" them. But I also tried opening https://github.com/tomahawkins/ecu/blob/master/src/j1939_orig.dbc  and it is not possible even after "fixing" with CANdb++ (may be file is too big?)

**Comment by rkollataj** [comment]
There are two problems with the CANdb parser '\"' signs e.g.

CM_ SG_ 2566844670 EngPTOGvrnrCst_DecelerateSwitch "Switch signal of the PTO control activator which indicates that the activator is in the position to \"coast/decelerate\" the PTO";

and format of some of _BA messages e.g. 
BA_ "SystemSignalLongSymbol" SG_ 2566714366 EngTrbCmprssrBypssActtr2PrlmnryF "EngTrbCmprssrBypssActtr2PrlmnryFMI";

As a workaround remove lines: 6633-6637, 9224-18176.

This is a great testing data, thanks! I will try to fix it in GENIVI/CANdb.

**Comment by w0land** [comment]
@novalisek thanks for pointing it out. I'll create a ticker under https://github.com/GENIVI/CANdb as this is a issues with new opendbc dbc files.

**Comment by w0land** [comment]
Ticket is here: https://github.com/GENIVI/CANdb/issues/16

**Comment by novalisek** [comment]
Thanks for looking at that.

**Comment by mguentner** [comment]
@rkollataj 

at least the ba_ sg_ issue is fixed with https://github.com/GENIVI/CANdb/pull/29/files
