### ISSUE TITLE
Signal decoder do not parse signals correctly* when they are big-endian.

### ISSUE THREAD

**Issue by ozzdemir** [GENIVI/CANdevStudio#200]
Signal decoder does not parse signals when they are big-endian. There are two problems I observed.
  - CanSignalDecoderPrivate::decodeFrame() calls CanSignalDecoderPrivate::rawToSignal with littleEndian parameter being true (even if signal is bigendian) It might be due to parsing (did not inspected further) but hotfixed by hardcoding litteEndian parameter to be false (since all my signals were big endian)
  - CanSignalDecoderPrivate::rawToSignal() handles bitordering uniformly for both, solved it by following hotfix.
```C
//bit++;
if(littleEndian) bit++;
if(!littleEndian) bit--;
```
DBC I used is this one: [toyota_rav4h_2017_mod.dbc](https://github.com/GENIVI/CANdevStudio/files/4547530/toyota_rav4h_2017_mod.txt)

**Comment by rkollataj** [comment]
Fixed with #206 in v1.2.1
