### ISSUE TITLE
litter endian and big endian error

### ISSUE THREAD

**Issue by hadwin2017** [GENIVI/CANdevStudio#202]
`

switch (sig.byteOrder) {
--
  | case 0:
  | // Little endian
  | littleEndian = true;
  | break;
  |  
  | case 1:
  | // Big endian
  | littleEndian = false;
  | break;
  |  
  | default:
  | cds_error("byte order {} not suppoerted", sig.byteOrder);
  | continue;
  | }

`

here, Intel is Little endian, and byteOrder is 1, Motorola is Big endian and byteOrder is 0

**Comment by rkollataj** [comment]
@hadwin2017 Not sure if I get your comment right. Do you mean that biteOrder is wrong? I based the code on http://read.pudn.com/downloads766/ebook/3041455/DBC_File_Format_Documentation.pdf

Extract:
byte_order = '0' | '1' ; (* 0=little endian, 1=big endian *)
The byte_format is 0 if the signal's byte order is Intel (little endian) or 1 if the byte
order is Motorola (big endian).

**Comment by SNL5943** [comment]
@rkollataj I think the reference file above is outdated and not valid anymore.
According this Repo [https://github.com/stefanhoelzl/CANpy/blob/master/docs/DBC_Specification.md] and this link [http://socialledge.com/sjsu/index.php/DBC_Format#:~:text=DBC%20file%20is%20a%20proprietary,bytes%20of%20CAN%20message%20data.&text=Essentially%2C%20each%20%22message%22%20defined,members%20of%20the%20C%20structure.](url) , the byteformat is 1 if the signal's byte order is little-endian and vice versa

**Comment by rkollataj** [comment]
@SNL5943 The document I shared comes from Vector which is DBC "inventor". I believe that this source is more relevant than sites that are trying to reverse engineer the format. I will leave this issue open and will try to verify endianess in CANoe when I will get a chance.

**Comment by SNL5943** [comment]
One finding, I've review [dbcparser.cpp](https://github.com/GENIVI/CANdb/blob/master/src/dbcparser.cpp) from CANdb, at line 251 as below:
` CANsignal::ByteOrder byteOrder = (take_back(numbers) == 0) ?
                    CANsignal::Motorola : CANsignal::Intel;`
I don't have any Vector hardware or software so can not verify with them.

**Comment by jenszo** [comment]
I am working with a major OEM's DBCs on a regular basis which have been built and engineered using mainly Vector Hard-  and Software. I can confirm that the current endinaness implementation of CANdb++ is perfectly valid and co-exist just fine with Vector products.

**Comment by rkollataj** [comment]
Fixed with #206 in v1.2.1
