### ISSUE TITLE
building for macOS-arm64 but attempting to link with file built for macOS-x86_64

### ISSUE THREAD

**Issue by D300** [GENIVI/CANdevStudio#243]
Hey,
i´m on an M1. is there a way to build the library for x86_64?

```
cd /Users/d300/Qt5.12.0/5.12.0/Src 
./configure -developer-build -xplatform macos-clang-arm64 -nomake examples -nomake tests

```

console printed:
+ cd qtbase
+ /Users/d300/Qt5.12.0/5.12.0/Src/qtbase/configure -top-level -developer-build -xplatform macos-clang-arm64 -nomake examples -nomake tests
Creating qmake...
................................................................................................Done.
Info: creating super cache file /Users/d300/Qt5.12.0/5.12.0/Src/.qmake.super
Info: creating cache file /Users/d300/Qt5.12.0/5.12.0/Src/.qmake.cache
ERROR: Invalid target platform 'macos-clang-arm64'.

**Comment by willson556** [comment]
I just built this project. I installed Qt5, CMake, & Ninja using [Homebrew](https://brew.sh):
```sh
brew install qt5 cmake ninja
```

Then I was able to configure and build the project:

```sh
git clone https://github.com/GENIVI/CANdevStudio.git
cd CANdevStudio
cmake -S. -Bbuild -GNinja -DCMAKE_PREFIX_PATH=$(brew --prefix qt5)/lib/cmake
cd build
ninja
``

**Comment by rkollataj** [comment]
Thanks @willson556 for the clear instructions. I will update the readme respectively.
